runtime: python39

instance_class: F2

handlers:
  - url: /static
    static_dir: staticfiles/ # Menggunakan direktori staticfiles

  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
